/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FeaturePropertiesDialog: typeof import('./src/components/FeaturePropertiesDialog.vue')['default']
    LayerControl: typeof import('./src/components/LayerControl.vue')['default']
    LocationsLayer: typeof import('./src/components/LocationsLayer.vue')['default']
    MapComponent: typeof import('./src/components/MapComponent.vue')['default']
    MapLayer: typeof import('./src/components/MapLayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeSeriesChart: typeof import('./src/components/TimeSeriesChart.vue')['default']
    TransectDialog: typeof import('./src/components/TransectDialog.vue')['default']
    WMTSLayer: typeof import('./src/components/WMTSLayer.vue')['default']
  }
}
